swarmsible_hetzner_manager_count: 3
swarmsible_hetzner_manager_server_type: cx21

swarmsible_hetzner_worker_count: 5
swarmsible_hetzner_worker_server_type: cx21

swarmsible_hetzner_server_image: ubuntu-20.04
swarmsible_hetzner_server_location: nbg1

swarmsible_hetzner_loadbalancer_type: lb11
swarmsible_hetzner_loadbalancer_dns_A:
  - zone: nfcompose-cloud.de
    record: "*.mytest-swarm.nfcompose-cloud.de"
    ttl: "7200"
swarmsible_hetzner_loadbalancer_dns_AAAA:
  - zone: nfcompose-cloud.de
    record: "*.mytest-swarm.nfcompose-cloud.de"
    ttl: "7200"
swarmsible_hetzner_loadbalancer_certificate_name: "swarmlb-certs"
swarmsible_hetzner_loadbalancer_certificate_domain_names: 
  - "*.mytest-swarm.nfcompose-cloud.de"
  - "*.mgmt.mytest-swarm.nfcompose-cloud.de"
swarmsible_hetzner_loadbalancer_certificate_type: 'managed'

swarmsible_hetzner_managers_part_of_lb: true

swarmsible_swarmsible_hetzner_ansible_root_ssh_key_name: ansible_root_rsa

swarmsible_hetzner_ansible_root_ssh_key: "{{ CWD }}/ssh_keys/root_rsa.pub"

swarmsible_hetzner_swarm_network_name: swarm_network
